# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.setAttribute(QtCore.Qt.WidgetAttribute.WA_StyledBackground, True)
        menu.setStyleSheet('background: #f9e1d4;')

        btn_style = '''
            font: 10pt "Segoe UI";
            background: rgba(0, 0, 0, 0);
            border: 0px;
            outline: none;
        '''

        self.home_btn = QtWidgets.QPushButton(parent=menu)
        self.home_btn.setGeometry(QtCore.QRect(22, 219, 86, 86))
        self.home_btn.setStyleSheet(btn_style)
        self.home_btn.setObjectName("home_btn")

        self.history_btn = QtWidgets.QPushButton(parent=menu)
        self.history_btn.setGeometry(QtCore.QRect(22, 405, 86, 86))
        self.history_btn.setStyleSheet(btn_style)
        self.history_btn.setObjectName("history_btn")

        self.profile_btn = QtWidgets.QPushButton(parent=menu)
        self.profile_btn.setGeometry(QtCore.QRect(22, 591, 86, 86))
        self.profile_btn.setStyleSheet(btn_style)
        self.profile_btn.setObjectName("profile_btn")

        self.refresh_btn = QtWidgets.QPushButton(parent=menu)
        self.refresh_btn.setGeometry(QtCore.QRect(41, 800, 50, 50))
        self.refresh_btn.setStyleSheet(btn_style)
        self.refresh_btn.setObjectName("refresh_btn")

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("Form", "Form"))
