# Form implementation generated from reading ui file '.\profile_vertical.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from help import get_font


class Ui_Form(object):
    def setupUi(self, ProfileVertical):
        ProfileVertical.setObjectName("ProfileVertical")

        self.pfp = QtWidgets.QLabel(parent=ProfileVertical)
        self.pfp.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.pfp.setStyleSheet(
            "background: #d0d0d0;\n"
            "border-radius: 50px;\n"
            "border: 1px solid #ccc;"
        )
        self.pfp.setText("")
        self.pfp.setObjectName("pfp")

        self.nickname = QtWidgets.QLabel(parent=ProfileVertical)
        self.nickname.setGeometry(QtCore.QRect(0, 100, 100, 24))
        font = get_font()
        self.nickname.setFont(font)
        self.nickname.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.nickname.setStyleSheet(
            "border: 0px;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #D45B69;"
        )
        self.nickname.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nickname.setObjectName("nickname")

        self.retranslateUi(ProfileVertical)
        QtCore.QMetaObject.connectSlotsByName(ProfileVertical)

    def retranslateUi(self, ProfileVertical):
        _translate = QtCore.QCoreApplication.translate
        ProfileVertical.setWindowTitle(_translate("ProfileVertical", "Form"))
        self.nickname.setText(_translate("ProfileVertical", "Nickname"))
