# Form implementation generated from reading ui file '.\profile_info.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from help import get_font


class Ui_profileInfo(object):
    def setupUi(self, profileInfo):
        profileInfo.setObjectName("profileInfo")
        profileInfo.setAttribute(QtCore.Qt.WidgetAttribute.WA_StyledBackground, True)
        profileInfo.setStyleSheet(
            "background: #f8e8e9;\n"
            "border-radius: 20px;\n"
            "border: 1px solid #ccc;"
        )

        self.pfp = QtWidgets.QLabel(parent=profileInfo)
        self.pfp.setGeometry(QtCore.QRect(25, 16, 144, 144))
        self.pfp.setStyleSheet(
            "background: #d0d0d0;\n"
            "border-radius: 72px;\n"
            "border: 1px solid #ccc;"
        )
        self.pfp.setText("")
        self.pfp.setObjectName("pfp")

        self.nickname = QtWidgets.QLabel(parent=profileInfo)
        self.nickname.setGeometry(QtCore.QRect(180, 42, 751, 51))
        font = get_font()
        font.setPointSize(26)
        self.nickname.setFont(font)
        self.nickname.setStyleSheet(
            "color: #D45B69;\n"
            "border: none;\n"
            ""
        )
        self.nickname.setObjectName("nickname")

        self.subscribers = QtWidgets.QLabel(parent=profileInfo)
        self.subscribers.setGeometry(QtCore.QRect(181, 89, 200, 30))
        font = get_font()
        font.setPointSize(16)
        self.subscribers.setFont(font)
        self.subscribers.setStyleSheet("border: none")
        self.subscribers.setObjectName("subscribers")

        self.subscribe_btn = QtWidgets.QPushButton(parent=profileInfo)
        self.subscribe_btn.setGeometry(QtCore.QRect(390, 89, 120, 30))
        font = get_font()
        font.setPointSize(12)
        self.subscribe_btn.setFont(font)
        self.subscribe_btn.setStyleSheet(
            "background: #FF6D6D;"
            "border: 1px solid #ccc;"
            "border-radius: 15px;"
            "color: white;"
            "font-size: 14px;"
            "font-weight: bold;"
        )
        self.subscribe_btn.setObjectName("subscribe_btn")

        self.logout_btn = QtWidgets.QPushButton(parent=profileInfo)
        self.logout_btn.setGeometry(QtCore.QRect(947, 15, 41, 41))
        self.logout_btn.setStyleSheet(
            "border: none;\n"
            "background: transparent;"
        )
        self.logout_btn.setText("")
        self.logout_btn.setObjectName("logout_btn")

        self.retranslateUi(profileInfo)
        QtCore.QMetaObject.connectSlotsByName(profileInfo)

    def retranslateUi(self, profileInfo):
        _translate = QtCore.QCoreApplication.translate
        profileInfo.setWindowTitle(_translate("profileInfo", "Form"))
        self.nickname.setText(_translate("profileInfo", "Nickname"))
        self.subscribers.setText(_translate("profileInfo", "Subscribers"))
        self.subscribe_btn.setText(_translate("profileInfo", "Subscribe"))
