# Form implementation generated from reading ui file 'topbar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from help import get_font


class Ui_topbar(object):
    def setupUi(self, topbar):
        topbar.setObjectName("topbar")

        self.searchbar = QtWidgets.QLineEdit(parent=topbar)
        self.searchbar.setGeometry(QtCore.QRect(30, 20, 1010, 52))
        font = get_font()
        font.setPointSize(12)
        self.searchbar.setFont(font)
        self.searchbar.setAccessibleDescription("")
        self.searchbar.setStyleSheet(
            "border-radius: 25px;\n"
            "border: 1px solid #ccc;\n"
            "padding-left: 12px;\n"
            "padding-top: 3px;"
            "outline: none;"
        )
        self.searchbar.setObjectName("searchbar")

        self.search_btn = QtWidgets.QPushButton(parent=topbar)
        self.search_btn.setGeometry(QtCore.QRect(983, 25, 42, 42))
        self.search_btn.setStyleSheet(
            "border: 0px;\n"
        )
        self.search_btn.setObjectName("search_btn")

        self.retranslateUi(topbar)
        QtCore.QMetaObject.connectSlotsByName(topbar)

    def retranslateUi(self, topbar):
        _translate = QtCore.QCoreApplication.translate
        self.searchbar.setPlaceholderText(_translate("topbar", "Search"))
