# Form implementation generated from reading ui file '.\video_horizontal.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from help import get_font


class Ui_video(object):
    def setupUi(self, video):
        video.setObjectName("video")
        video.setAttribute(QtCore.Qt.WidgetAttribute.WA_StyledBackground, True)
        video.setStyleSheet(
            "border-radius: 20px;\n"
            "border: 1px solid #ccc;\n"
            "background: #f3ded4"
        )

        self.thumnbnail = QtWidgets.QLabel(parent=video)
        self.thumnbnail.setGeometry(QtCore.QRect(0, 0, 327, 165))
        font = get_font()
        font.setPointSize(26)
        self.thumnbnail.setFont(font)
        self.thumnbnail.setAutoFillBackground(False)
        self.thumnbnail.setStyleSheet(
            "border-radius: 20px;\n"
            "border: 1px solid #ccc;\n"
            "background: #d9d9d9"
        )
        self.thumnbnail.setText("")
        self.thumnbnail.setObjectName("thumnbnail")

        self.avatar = QtWidgets.QLabel(parent=video)
        self.avatar.setGeometry(QtCore.QRect(340, 78, 35, 35))
        self.avatar.setStyleSheet(
            "border-radius: 17px;\n"
            "border: 1px solid #ccc;\n"
            "background: #000000\n"
            ""
        )
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")

        self.title = QtWidgets.QLabel(parent=video)
        self.title.setGeometry(QtCore.QRect(340, 16, 211, 50))
        self.title.setWordWrap(True)
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        font = get_font()
        font.setPointSize(15)
        self.title.setFont(font)
        self.title.setStyleSheet(
            "border: 0px;\n"
            "background: rgba(0, 0, 0, 0)"
        )
        self.title.setObjectName("title")

        self.nickname = QtWidgets.QLabel(parent=video)
        self.nickname.setGeometry(QtCore.QRect(380, 85, 151, 20))
        font = get_font()
        font.setPointSize(13)
        self.nickname.setFont(font)
        self.nickname.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.nickname.setStyleSheet(
            "border: 0px;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #D45B69;"
        )
        self.nickname.setObjectName("nickname")

        self.views = QtWidgets.QLabel(parent=video)
        self.views.setGeometry(QtCore.QRect(340, 130, 111, 20))
        font = get_font()
        font.setPointSize(11)
        self.views.setFont(font)
        self.views.setStyleSheet(
            "border: 0px;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #635D5D;"
        )
        self.views.setObjectName("views")

        self.date = QtWidgets.QLabel(parent=video)
        self.date.setGeometry(QtCore.QRect(460, 130, 91, 20))
        font = get_font()
        font.setPointSize(11)
        self.date.setFont(font)
        self.date.setStyleSheet(
            "border: 0px;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #635D5D;"
        )
        self.date.setObjectName("date")

        self.retranslateUi(video)
        QtCore.QMetaObject.connectSlotsByName(video)

    def retranslateUi(self, video):
        _translate = QtCore.QCoreApplication.translate
        video.setWindowTitle(_translate("video", "Dialog"))
        self.title.setText(_translate("video", "Title"))
        self.nickname.setText(_translate("video", "Nickname"))
        self.views.setText(_translate("video", "Views"))
        self.date.setText(_translate("video", "Date"))
