# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from help import get_font


class Ui_video(object):
    def setupUi(self, video):
        video.setObjectName("video")
        video.setAttribute(QtCore.Qt.WidgetAttribute.WA_StyledBackground, True)
        video.setStyleSheet(
            "border-radius: 20px;\n"
            "border: none;\n"
            "background: #f3ded4;"
        )

        self.thumnbnail = QtWidgets.QLabel(parent=video)
        self.thumnbnail.setGeometry(QtCore.QRect(-1, -1, 332, 167))
        font = get_font()
        font.setPointSize(26)
        self.thumnbnail.setFont(font)
        self.thumnbnail.setAutoFillBackground(False)
        self.thumnbnail.setStyleSheet(
            "border-radius: 20px;\n"
            "border: none;\n"
            "background: #d9d9d9"
        )
        self.thumnbnail.setText("")
        self.thumnbnail.setObjectName("thumnbnail")

        self.avatar = QtWidgets.QLabel(parent=video)
        self.avatar.setGeometry(QtCore.QRect(12, 178, 35, 35))
        self.avatar.setStyleSheet(
            "border-radius: 17px;\n"
            "border: none;\n"
            "background: #000000\n"
        )
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")

        self.title = QtWidgets.QLabel(parent=video)
        self.title.setGeometry(QtCore.QRect(60, 168, 251, 21))
        font = get_font()
        font.setPointSize(12)
        self.title.setFont(font)
        self.title.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0)"
        )
        self.title.setObjectName("title")

        self.nickname = QtWidgets.QLabel(parent=video)
        self.nickname.setGeometry(QtCore.QRect(60, 187, 251, 21))
        font = get_font()
        font.setPointSize(12)
        self.nickname.setFont(font)
        self.nickname.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.nickname.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #D45B69;"
        )
        self.nickname.setObjectName("nickname")

        self.views = QtWidgets.QLabel(parent=video)
        self.views.setGeometry(QtCore.QRect(60, 205, 100, 20))
        font = get_font()
        font.setPointSize(9)
        self.views.setFont(font)
        self.views.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #635D5D;"
        )
        self.views.setObjectName("views")

        self.date = QtWidgets.QLabel(parent=video)
        self.date.setGeometry(QtCore.QRect(200, 205, 61, 20))
        font = get_font()
        font.setPointSize(9)
        self.date.setFont(font)
        self.date.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #635D5D;"
        )
        self.date.setObjectName("date")

        # Добавляем QLabel для длительности видео
        self.duration_label = QtWidgets.QLabel(parent=video)
        self.duration_label.setGeometry(QtCore.QRect(260, 130, 60, 20))
        font = get_font()
        font.setPointSize(8)
        font.setBold(True)
        self.duration_label.setFont(font)
        self.duration_label.setStyleSheet(
            "background-color: rgba(0, 0, 0, 0.7);"
            "color: white;"
            "border-radius: 6px;"
            "padding: 2px 4px;"
        )
        self.duration_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.duration_label.setObjectName("duration_label")

        self.retranslateUi(video)
        QtCore.QMetaObject.connectSlotsByName(video)

    def retranslateUi(self, video):
        _translate = QtCore.QCoreApplication.translate
        video.setWindowTitle(_translate("video", "Dialog"))
        self.title.setText(_translate("video", "Title"))
        self.nickname.setText(_translate("video", "Nickname"))
        self.views.setText(_translate("video", "Views"))
        self.date.setText(_translate("video", "Date"))
        self.duration_label.setText(_translate("video", "0:00"))  # Значение по умолчанию