# Form implementation generated from reading ui file '.\video_profile.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from help import get_font


class Ui_Form:
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(992, 123)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_StyledBackground, True)
        Form.setStyleSheet(
            "background: #f8e8e9;"
            "border-radius: 20px;"
        )

        self.title = QtWidgets.QLabel(parent=Form)
        self.title.setGeometry(QtCore.QRect(10, 10, 971, 21))
        font = get_font()
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setStyleSheet(
            "border: 0px;"
            "color: #000;"
            "background: rgba(0, 0, 0, 0)"
        )
        self.title.setObjectName("title")

        self.views = QtWidgets.QLabel(parent=Form)
        self.views.setGeometry(QtCore.QRect(16, 96, 80, 20))
        font = get_font()
        font.setPointSize(10)
        self.views.setFont(font)
        self.views.setStyleSheet(
            "border: 0px;"
            "background: rgba(0, 0, 0, 0);"
            "color: #635D5D;"
        )
        self.views.setObjectName("views")

        self.date = QtWidgets.QLabel(parent=Form)
        self.date.setGeometry(QtCore.QRect(139, 96, 80, 20))
        font = get_font()
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setStyleSheet(
            "border: 0px;"
            "background: rgba(0, 0, 0, 0);"
            "color: #635D5D;"
        )
        self.date.setObjectName("date")

        self.like_btn = QtWidgets.QPushButton(parent=Form)
        self.like_btn.setGeometry(QtCore.QRect(840, 10, 30, 30))
        self.like_btn.setStyleSheet("background: transparent;")
        self.like_btn.setText("")
        self.like_btn.setObjectName("like_btn")

        self.dislike_btn = QtWidgets.QPushButton(parent=Form)
        self.dislike_btn.setGeometry(QtCore.QRect(920, 10, 30, 30))
        self.dislike_btn.setStyleSheet("background: transparent;")
        self.dislike_btn.setText("")
        self.dislike_btn.setObjectName("dislike_btn")

        self.likes_label = QtWidgets.QLabel(parent=Form)
        self.likes_label.setGeometry(QtCore.QRect(840, 45, 30, 20))
        self.likes_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = get_font()
        font.setPointSize(10)
        self.likes_label.setFont(font)
        self.likes_label.setStyleSheet(
            "border: none;"
            "background: rgba(0, 0, 0, 0);"
            "color: #635D5D;"
        )
        self.likes_label.setObjectName("likes_label")

        self.dislikes_label = QtWidgets.QLabel(parent=Form)
        self.dislikes_label.setGeometry(QtCore.QRect(920, 45, 30, 20))
        self.dislikes_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = get_font()
        font.setPointSize(10)
        self.dislikes_label.setFont(font)
        self.dislikes_label.setStyleSheet(
            "border: none;"
            "background: rgba(0, 0, 0, 0);"
            "color: #635D5D;"
        )
        self.dislikes_label.setObjectName("dislikes_label")

        self.pfp = QtWidgets.QLabel(parent=Form)
        self.pfp.setGeometry(QtCore.QRect(8, 40, 50, 50))
        self.pfp.setStyleSheet(
            "border-radius: 25px;"
            "border: none;"
            "background: #000000"
        )
        self.pfp.setText("")
        self.pfp.setObjectName("pfp")

        self.subscribers = QtWidgets.QLabel(parent=Form)
        self.subscribers.setGeometry(QtCore.QRect(63, 63, 131, 25))
        font = get_font()
        font.setPointSize(10)
        self.subscribers.setFont(font)
        self.subscribers.setStyleSheet(
            "border: 0px;"
            "background: rgba(0, 0, 0, 0);"
            "color: #635D5D;"
        )
        self.subscribers.setObjectName("subscribers")

        self.nickname = QtWidgets.QLabel(parent=Form)
        self.nickname.setGeometry(QtCore.QRect(63, 41, 131, 21))
        font = get_font()
        font.setPointSize(12)
        self.nickname.setFont(font)
        self.nickname.setContextMenuPolicy(
            QtCore.Qt.ContextMenuPolicy.NoContextMenu
        )
        self.nickname.setStyleSheet(
            "border: 0px;"
            "background: rgba(0, 0, 0, 0);"
            "color: #D45B69;"
        )
        self.nickname.setObjectName("nickname")

        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(193, 48, 120, 30))
        font = get_font()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(
            "background: #FF6D6D;"
            "border: 1px solid #ccc;"
            "border-radius: 15px;"
        )
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "profileUnderVideo"))
        self.date.setText(_translate("Form", "Date"))
        self.title.setText(_translate("Form", "Title"))
        self.views.setText(_translate("Form", "Views"))
        self.likes_label.setText(_translate("Form", "1000 likes"))
        self.dislikes_label.setText(_translate("Form", "1 dislike"))
        self.subscribers.setText(_translate("Form", "Subscribers"))
        self.nickname.setText(_translate("Form", "Nickname"))
        self.pushButton.setText(_translate("Form", "Subscribe"))
