# Form implementation generated from reading ui file '.\video_horizontal_long.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from help import get_font


class Ui_video(object):
    def setupUi(self, video):
        video.setObjectName("video")
        video.setAutoFillBackground(False)
        video.setAttribute(QtCore.Qt.WidgetAttribute.WA_StyledBackground, True)
        video.setStyleSheet(
            "border-radius: 20px;\n"
            "border: none;\n"
            "background: #f3ded4"
        )

        self.thumnbnail = QtWidgets.QLabel(parent=video)
        self.thumnbnail.setGeometry(QtCore.QRect(0, 0, 327, 165))
        font = get_font()
        font.setPointSize(26)
        self.thumnbnail.setFont(font)
        self.thumnbnail.setAutoFillBackground(False)
        self.thumnbnail.setStyleSheet(
            "border-radius: 20px;\n"
            "border: none;\n"
            "background: #d9d9d9"
        )
        self.thumnbnail.setText("")
        self.thumnbnail.setObjectName("thumnbnail")

        self.avatar = QtWidgets.QLabel(parent=video)
        self.avatar.setGeometry(QtCore.QRect(340, 78, 35, 35))
        self.avatar.setStyleSheet(
            "border-radius: 17px;\n"
            "border: none;\n"
            "background: #000000\n"
            ""
        )
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")

        self.title = QtWidgets.QLabel(parent=video)
        self.title.setGeometry(QtCore.QRect(340, 16, 530, 31))
        font = get_font()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0)"
        )
        self.title.setObjectName("title")

        self.nickname = QtWidgets.QLabel(parent=video)
        self.nickname.setGeometry(QtCore.QRect(380, 85, 151, 20))
        font = get_font()
        font.setPointSize(13)
        self.nickname.setFont(font)
        self.nickname.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.nickname.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #D45B69;"
        )
        self.nickname.setObjectName("nickname")

        self.views = QtWidgets.QLabel(parent=video)
        self.views.setGeometry(QtCore.QRect(340, 130, 111, 20))
        font = get_font()
        font.setPointSize(11)
        self.views.setFont(font)
        self.views.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #635D5D;"
        )
        self.views.setObjectName("views")

        self.date = QtWidgets.QLabel(parent=video)
        self.date.setGeometry(QtCore.QRect(460, 130, 91, 20))
        font = get_font()
        font.setPointSize(11)
        self.date.setFont(font)
        self.date.setStyleSheet(
            "border: none;\n"
            "background: rgba(0, 0, 0, 0);\n"
            "color: #635D5D;"
        )
        self.date.setObjectName("date")

        self.remove_btn = QtWidgets.QPushButton(parent=video)
        self.remove_btn.setGeometry(QtCore.QRect(905, 15, 41, 41))
        self.remove_btn.setStyleSheet(
            "border: none;\n"
            "background: transparent;"
        )
        self.remove_btn.setText("")
        self.remove_btn.setObjectName("remove_btn")

        # Добавляем QLabel для длительности видео
        self.duration_label = QtWidgets.QLabel(parent=video)
        self.duration_label.setGeometry(QtCore.QRect(260, 125, 60, 20))
        font = get_font()
        font.setPointSize(8)
        font.setBold(True)
        self.duration_label.setFont(font)
        self.duration_label.setStyleSheet(
            "background-color: rgba(0, 0, 0, 0.7);"
            "color: white;"
            "border-radius: 6px;"
            "padding: 2px 4px;"
        )
        self.duration_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.duration_label.setObjectName("duration_label")

        # Добавляем прогресс-бар для просмотренного времени
        self.progress_container = QtWidgets.QWidget(parent=video)
        self.progress_container.setGeometry(QtCore.QRect(0, 150, 327, 4))
        self.progress_container.setStyleSheet(
            "background-color: rgba(0, 0, 0, 0.3);"
            "border: none;"
            "border-radius: 2px;"
        )
        self.progress_container.setObjectName("progress_container")
        
        self.progress_bar = QtWidgets.QWidget(parent=self.progress_container)
        self.progress_bar.setGeometry(QtCore.QRect(0, 0, 0, 4))
        self.progress_bar.setStyleSheet(
            "background-color: #D45B69;"
            "border: none;"
            "border-radius: 2px;"
        )
        self.progress_bar.setObjectName("progress_bar")
        
        # Скрываем прогресс-бар по умолчанию
        self.progress_container.setVisible(False)

        self.retranslateUi(video)
        QtCore.QMetaObject.connectSlotsByName(video)

    def retranslateUi(self, video):
        _translate = QtCore.QCoreApplication.translate
        video.setWindowTitle(_translate("video", "Dialog"))
        self.title.setText(_translate("video", "Title"))
        self.nickname.setText(_translate("video", "Nickname"))
        self.views.setText(_translate("video", "Views"))
        self.date.setText(_translate("video", "Date"))
        self.duration_label.setText(_translate("video", "0:00"))